# Procesamiento de los datos del Dataset bo222k-1173.xyz

In [1]:
#dataset="bo222-200k-1173k"
dataset="prueba"

## Exploración de los datos

### Número de átomos por muestra

In [2]:
# Nombre del archivo
nombre_archivo = dataset+".xyz"

#Encontrar número de nuestras
with open(nombre_archivo, "r") as archivo:
    lista_atomos_en_molecula=[]
    for linea in archivo:
        linea=linea.split()
        if len(linea)==1:
            lista_atomos_en_molecula.append(linea[0])
# Crear un conjunto de números únicos en la lista
numeros_unicos = set(lista_atomos_en_molecula)

# Iterar sobre los números únicos y contar cuántas veces aparecen en la lista
for numero in numeros_unicos:
    veces_que_aparece = lista_atomos_en_molecula.count(numero)
    print(f"{veces_que_aparece} muestras tienen {numero} átomos cada una.")

if len(numeros_unicos)==1:
    numero_atomos=int(numeros_unicos.pop())
    print("Todas las muestras tienen el mismo número de átomos.")
else:
    print("Las muestras tienen distintos números de átomos.")

10 muestras tienen 222 átomos cada una.
Todas las muestras tienen el mismo número de átomos.


## Ejemplo de muestra

In [3]:
# Nombre del archivo
nombre_archivo = dataset+".xyz"
numero_de_muestras_a_imprimir=1

with open(nombre_archivo, "r") as archivo:
     # Inicializamos un contador de muestras
    contador_muestras = 0
    # Iteramos sobre las líneas del archivo
    for linea in archivo:
        # Si encontramos una línea que comienza con "MD_Step", incrementamos el contador
        if linea.startswith(str(numero_atomos)):
            contador_muestras += 1
            # Imprimimos la información de la muestra
            print(f"Muestra {contador_muestras}:\n{linea.strip()}")  # strip() elimina los espacios en blanco al principio y al final
            for _ in range(numero_atomos+1):
                print(str(archivo.readline().strip()))  # Imprimimos las siguientes 4 líneas (coordinadas de átomos)

            # Salto de línea para separar las muestras en la impresión
            print()

            # Si ya hemos impreso las dos primeras muestras, salimos del bucle
            if contador_muestras == numero_de_muestras_a_imprimir:
                break


Muestra 1:
222
MD_Step: 0 Total_energy = -392098.0704895295
H        12.5382170395        -7.6180493863        -8.3430311347        -0.39898648772126744        0.01952690778826339        0.5445614804687664
O        11.5886714189        -7.9580544718        -6.7810444904        0.31135376709519236        -0.056585372324846304        -0.07864721833014225
H        3.3587227872        -9.7510008565        -9.363537438        0.36682549685425936        -0.30268877340151773        -0.2658061311968897
O        9.8455171785        -3.1027899525        -7.2826422674        -0.08007644326414802        0.4438071698564543        0.2724695877759438
H        8.3874793281        9.8250429989        -5.3336833903        -0.067055722804807        -0.23375081267784817        0.29892145906568657
O        2.0539681079        -8.9315728042        -8.4516504011        -0.15112827260809886        0.3293702030833735        -0.049309828596247024
O        2.3448380358        -3.0549670935        -8.1765046048  

Unicamente los datos correspondientes a la energía total del arreglo (meV), las posiciones(A) y fuerzas de los átomos son de nuestro intéres(meV/A).

## Procesamiento de los datos

### Importación de módulos

In [4]:
import numpy as np
import h5py
import os
import shutil

### Creación de la carpeta auxiliar temp

In [5]:
carpetas=["temp","datos-procesados"]
for nombre_carpeta in carpetas:
    if os.path.exists(nombre_carpeta) and os.path.isdir(nombre_carpeta):
        shutil.rmtree(nombre_carpeta)
        os.mkdir(nombre_carpeta)
    else:
        os.mkdir(nombre_carpeta)

### Funciones 

In [6]:
#Intercamcio de elemento por su posición en la tabla periodica
def posicion_en_tabla_periodica(elemento_quimico):
    tabla_periodica = {
        "H": 1, "He": 2, "Li": 3, "Be": 4, "B": 5, "C": 6, "N": 7, "O": 8, "F": 9, "Ne": 10,
        "Na": 11, "Mg": 12, "Al": 13, "Si": 14, "P": 15, "S": 16, "Cl": 17, "Ar": 18,
        "K": 19, "Ca": 20, "Sc": 21, "Ti": 22, "V": 23, "Cr": 24, "Mn": 25, "Fe": 26, "Ni": 27, "Co": 28,
        "Cu": 29, "Zn": 30, "Ga": 31, "Ge": 32, "As": 33, "Se": 34, "Br": 35, "Kr": 36,
        "Rb": 37, "Sr": 38, "Y": 39, "Zr": 40, "Nb": 41, "Mo": 42, "Tc": 43, "Ru": 44, "Rh": 45, "Pd": 46,
        "Ag": 47, "Cd": 48, "In": 49, "Sn": 50, "Sb": 51, "Te": 52, "I": 53, "Xe": 54,
        "Cs": 55, "Ba": 56, "La": 57, "Hf": 72, "Ta": 73, "W": 74, "Re": 75, "Os": 76, "Ir": 77, "Pt": 78,
        "Au": 79, "Hg": 80, "Tl": 81, "Pb": 82, "Bi": 83, "Th": 90, "Pa": 91, "U": 92, "Np": 93, "Pu": 94,
        "Am": 95, "Cm": 96, "Bk": 97, "Cf": 98, "Es": 99, "Fm": 100
    }

    elemento = elemento_quimico.capitalize()
    if elemento in tabla_periodica:
        return tabla_periodica[elemento]
    else:
        return None

In [7]:
# energias atomicas
def atom_energy(elemento_quimico):
    energias_atomicas = {
        1:-0.500272784191*27.21138602,
        7:-242.365764213*27.21138602,
        8:-74.9555225243*27.21138602,
        13:-242.365764213*27.21138602
    }

    elemento = int(elemento_quimico)
    if elemento in energias_atomicas:
        return energias_atomicas[elemento]
    else:
        return None

### Guardar los datos seleccionados en archivos .data

In [8]:
# Nombre del archivo
nombre_archivo = dataset+".xyz"
with open(nombre_archivo, "r") as archivo:
    # Iteramos sobre las líneas del archivo
    for linea in archivo:
        #Convertimos la linea en una lista
        linea=linea.split()
        # Si la longitud de la linea es 1, se trata del numero de átomos y el comienzo de la muestra
        if len(linea)==1:
            # inicialización de numeros atomicos
            atomos_muestra=[]
            numero_atomos_muestra=int(linea[0])
            # Guardado y Procesamiento de los datos de una muestra
            for numero_linea_en_muestra in range(numero_atomos_muestra+1):
                # Seleccionamos la siguiente linea
                linea_en_muestra=archivo.readline().strip()
                # convertimos a una lista la linea seleccionadda
                linea_en_muestra=linea_en_muestra.split()
##################################################################################
                # Guardamos la energia total en una variable
                if len(linea_en_muestra)==5:
                    energia_total=float(linea_en_muestra[-1])
             
                # Guardado de las fuerzas y posiciones
                if len(linea_en_muestra)==7:
                    # procesamiento 
                    z=posicion_en_tabla_periodica(linea_en_muestra[0])
                    atomos_muestra.append(z)
                    n_type=[z]

                    n_pos=[linea_en_muestra[1],linea_en_muestra[2],linea_en_muestra[3]]

                    n_force=[linea_en_muestra[4],linea_en_muestra[5],linea_en_muestra[6]]

                    # Guardado
                    with open("temp/pos.data", "a") as file:
                        line = " ".join(str(elemento) for elemento in n_pos)
                        file.write(line + "\n")
                    with open("temp/type.data", "a") as file:
                        line = " ".join(str(elemento) for elemento in n_type)
                        file.write(line + "\n")
                    with open("temp/force.data", "a") as file:
                        line = " ".join(str(elemento) for elemento in n_force)
                        file.write(line + "\n")

##################################################################################
                if numero_linea_en_muestra==(numero_atomos_muestra):
                    # Aplicar la función atom_energy a cada elemento de la lista usando map
                    resultados = map(atom_energy, atomos_muestra)

                    # Sumar los resultados
                    suma_resultados = sum(resultados)

                    # Calcular el promedio dividiendo la suma por el número de átomos en la muestra
                    numero_de_atomos = len(atomos_muestra)
                    n_energy=(energia_total-suma_resultados) / numero_de_atomos
                    n_energy=[n_energy]
                    with open("temp/energy.data", "a") as file:
                        line = " ".join(str(elemento) for elemento in n_energy)
                        file.write(line + "\n")

### Cargar datos en numpy arrays (nuevo) 

In [9]:
from itertools import islice
# Esta lista se calculo al principio
lista_atomos_en_molecula = [int(num) for num in lista_atomos_en_molecula]

linea_energy=1
linea_type=1
linea_pos=1
linea_force=1

energy=[]
pos=[]
types=[]
forces=[]


for num_atomos in lista_atomos_en_molecula:    
    with open("temp/energy.data", 'r') as archivo:
        linea=next(islice(archivo, linea_energy - 1, None), None)
        energia=float(np.array(linea))
    energy.append(energia)
    linea_energy=linea_energy+1

    with open("temp/type.data", 'r') as f:
        # Utiliza islice para saltar las líneas hasta llegar a la posición de inicio
        lineas = islice(f, linea_type - 1, linea_type + num_atomos-1)
        # Ahora lineas contiene solo las líneas que quieres
        muestra=[]
        for linea in lineas:
            # Convierte cada valor a entero y agrégalo a la lista muestra
            values = [int(val) for val in linea.strip().split()]
            muestra.extend(values)
    types.append(muestra)
    linea_type=linea_type+num_atomos


    with open("temp/pos.data", 'r') as f:
        # Utiliza islice para saltar las líneas hasta llegar a la posición de inicio
        lineas = islice(f, linea_pos - 1, linea_pos + num_atomos-1)
        # Ahora lineas contiene solo las líneas que quieres
        muestra=[]
        for linea in lineas:
            # Convierte cada valor a número flotante y agrégalo a la lista muestra
            values = [float(val) for val in linea.strip().split()]
            muestra.append(values)
    pos.append(muestra)
    linea_pos=linea_pos+num_atomos

    with open("temp/force.data", 'r') as f:
        # Utiliza islice para saltar las líneas hasta llegar a la posición de inicio
        lineas = islice(f, linea_force - 1, linea_force + num_atomos-1)
        # Ahora lineas contiene solo las líneas que quieres
        muestra=[]
        for linea in lineas:
            # Convierte cada valor a número flotante y agrégalo a la lista muestra
            values = [float(val) for val in linea.strip().split()]
            muestra.append(values)
    forces.append(muestra)
    linea_force = linea_force + num_atomos

energy = np.array(energy, dtype=np.float64)
pos = np.array(pos, dtype=np.float64)
types = np.array(types, dtype=np.int32)
forces = np.array(forces, dtype=np.float64)


### Guardar en archivo .h5 (sin fuerzas)

In [10]:
########################################################
filename = "datos-procesados/"+dataset+".h5"##
########################################################

f=h5py.File(filename, "w")

##############################
group_name = dataset##
##############################

group = f.create_group(group_name)

# Guardar datos en el grupo
group.create_dataset("types", data=types)
group.create_dataset("pos", data=pos)
group.create_dataset("energy", data=energy)

f.close()

### Guardar en archivo .h5 (con fuerzas)

In [11]:
########################################################
filename = "datos-procesados/"+dataset+"-f.h5"##
########################################################

f=h5py.File(filename, "w")

##############################
group_name = dataset
##############################

group = f.create_group(group_name)

# Guardar datos en el grupo
group.create_dataset("types", data=types)
group.create_dataset("pos", data=pos)
group.create_dataset("energy", data=energy)
group.create_dataset("forces", data=forces)

f.close()

### Eliminación de la carpeta auxiliar

In [12]:
nombre_carpeta="temp"
if os.path.exists(nombre_carpeta) and os.path.isdir(nombre_carpeta):
    shutil.rmtree(nombre_carpeta)

## Exploaracion de una muestra

In [13]:
filename = "datos-procesados/"+dataset+"-f.h5"

f=h5py.File(filename, "r")
group_name = dataset
group=f[group_name]
indice_muestra=4

In [14]:
print(group["types"][indice_muestra])


[ 1  8  1  8  1  8  8  8  8  1  1  8  8  8  8  1  1  1  8  1  8  1 13  8
  1  1  1  8  1  8  8  1  8 13  1  1 13  8  1  8  8  1  8 13  1  1 13  8
  1  8  8  1  8  1  1  8 13  1  1  8  8  1  8  1 13 13  1  8  1  8  8  8
  1 13 13  1  8  1  1  8  8  8  1 13 13  1  1  8  1  8  8  1 13  8  1  1
  8  1  8  8  1  8 13 13  8  1  8  8  1  8 13 13  8  1  8  8  1  8  1  8
 13  1  8  8  1  8  1 13 13  1  8  1  8  8  8  1 13 13  1  8  1  8  8  8
  1 13 13  1  1  8  1  8  8  1 13  1  8  1  1  8  1  8  8  1  8 13  1  1
 13  8  1  8  8  1  8 13  1  1 13  8  1  8  8  8  1  1  8 13  1  8  1  8
  1  8  1  8  8  8  1  1  8  1  1  8  8  8  1  1  1  8  8  1  1  1  1  1
  1  1  1  1  1  1]


In [15]:
print(group["pos"][indice_muestra])


[[ 1.25586142e+01 -7.60693616e+00 -8.23849858e+00]
 [ 1.15855791e+01 -7.96759631e+00 -6.76283243e+00]
 [ 3.44465335e+00 -9.81232849e+00 -9.35121781e+00]
 [ 9.82832120e+00 -3.12228384e+00 -7.28648110e+00]
 [ 8.39336261e+00  9.79694671e+00 -5.23484537e+00]
 [ 2.06456924e+00 -8.92915664e+00 -8.45680491e+00]
 [ 2.36339894e+00 -3.07878959e+00 -8.19441005e+00]
 [ 4.69105820e+00  5.47537743e+00 -7.22175274e+00]
 [ 2.94010106e+00  1.10136419e+01 -7.04353425e+00]
 [ 3.88225536e+00  1.16045412e+01 -8.44269215e+00]
 [-3.09661821e+00 -1.00614231e+01 -1.05015673e+01]
 [-2.44254877e+00 -1.00357405e+01 -8.78622655e+00]
 [-4.73722542e+00 -4.81787014e+00 -8.91626179e+00]
 [-2.40390339e+00  4.76557764e+00 -8.24163369e+00]
 [-2.27564818e+00  9.89847111e+00 -7.32167595e+00]
 [-3.29099142e-01 -9.73644313e+00 -8.78652892e+00]
 [-1.26558327e+01 -6.71511837e+00  1.79979968e-01]
 [-5.53972169e-01  1.07355811e+01 -7.46442096e+00]
 [ 1.34825441e+01 -1.05996606e+01 -2.71895318e+00]
 [ 1.21586429e+01  7.55554895e+

In [16]:
print(group["energy"][indice_muestra])


-5.333902544775655


In [17]:
print(group["forces"][indice_muestra])

[[ 1.30289572e-01  1.65041202e-01 -3.52517353e-01]
 [-2.29809368e-01 -1.71747354e-01  8.03225184e-01]
 [-2.54675696e-01  1.71432050e-01  2.10133336e-01]
 [-9.72410984e-02  5.29367612e-01  2.24646561e-01]
 [ 1.62668624e-01  1.32164766e-01  1.13573169e-01]
 [ 5.98618877e-01 -3.91816997e-01 -6.64937341e-01]
 [-1.28155614e+00 -1.20023665e+00 -2.00479198e-01]
 [-1.31279001e+00 -1.18736340e-01 -1.03524031e+00]
 [-2.57508276e-01  1.69873066e-01 -2.07998636e-01]
 [-1.34315056e-02  7.53751345e-02 -2.34599220e-01]
 [-9.49493038e-01 -1.98319749e-01 -2.02952335e+00]
 [ 1.06489178e+00  8.51298430e-01  1.89722601e+00]
 [-2.00355606e+00 -9.11136068e-01  3.79309011e-01]
 [-7.12953591e-02 -6.11261260e-02 -5.25695480e-01]
 [ 1.58889512e+00  1.42017851e+00 -6.50018524e-01]
 [-1.97043422e-01  1.18808156e-01  3.99699666e-01]
 [ 5.00658569e-01  4.11531852e-01  1.03414715e+00]
 [-8.53104738e-01 -7.09905234e-01  7.64356529e-02]
 [-6.17688458e-01  4.24578464e-01 -6.28291832e-01]
 [ 5.13951940e-01  5.51675996e-

In [18]:
f.close()